# Generated by Django 4.1.1 on 2022-10-06 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apm", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="apirequest",
            name="view_name",
            field=models.CharField(
                editable=False,
                help_text="The name of the function/class that handled this request",
                max_length=255,
                null=True,
                verbose_name="View name",
            ),
        ),
    ]
